import Head from 'next/head'
import * as React from 'react';

import Layout from '../components/layout/layout';
export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>deepak rawat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />

    </React.Fragment>
  )
}
