import React, { useState } from "react";
import Head from 'next/head'
import NavbarComponent from "../../components/navbar/navbar";
import Link from "next/link";
import CardComponent from "../../components/CardComponent/CardComponent";
import { Nav, Button } from "react-bootstrap";


import styles from './index.module.css'
import TechnicalBlogs from "../../components/TechnicalBlogs/TechnicalBlogs";
import PerceptionBlogs from "../../components/PerceptionBlogs/PerceptionBlogs";

function Index() {

    const [selectedBlogCategory, setSelectedBlogCategory] = useState('Perceptions')

    const selectedBlogCategoryHandler = (event) =>{
        console.log(event)
        setSelectedBlogCategory(event.target.value)
    }

  return (
    <React.Fragment>
       <Head>
        <title>Deepak | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <div className={styles.blogNav}>
        
        <div variant="pills" onClick = {(e)=> selectedBlogCategoryHandler(e)} style={{width:"20%"}} className ={styles.buttonParent}>
        <div style ={{padding:"10px"}}>
            <Button size="lg" variant={selectedBlogCategory === "Perceptions" ? "dark" : "light"} value = "Perceptions">Perceptions</Button>{' '}
        </div>
        <div style ={{padding:"10px"}}>
            <Button size="lg" variant={selectedBlogCategory === "Technical" ? "dark" : "light"} value = "Technical">Technical</Button>{' '}
        </div>
        </div>
      </div>

      {selectedBlogCategory === "Perceptions" ? <div className ={styles.blogBody}><PerceptionBlogs /></div> : <div><TechnicalBlogs /></div>}

    </React.Fragment>
  );
}

export default Index;
